version: "3"
services:
  web:
    container_name: netzetService
    build:
      dockerfile: Dockerfile.dev
      context: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/server
    environment:
      DB_DATABASE: netzet
      DB_USERNAME: admin
      DB_PASSWORD: admin
      DB_HOST: db
      DB_PORT: 3306
      SYNCHRONIZE: 'true'
      APPLICATION_SERVER_PORT: 3000
      APP_FORCE_SHUTDOWN_SECOND: 30

  # Database
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: netzet
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root